name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build
        run: |
          wget -O bld.jar "https://hub.spigotmc.org/jenkins/job/BuildTools/171/artifact/target/BuildTools.jar"
          java -jar bld.jar
      - uses: actions/upload-artifact@v3
        with:
          name: Release
          path: '*'
